### ISSUE TITLE
mldeploy using exported resources is not deploying in order

### ISSUE THREAD

**Issue by arulsiva21** [marklogic-community/ml-gradle#262] opened 2017-11-28 13:35 UTC
i'm facing issue on deploying exported resources in different marklogic host. It seems like they are not getting deployed in order if roles are inherited.  Is there anyway to avoid these failures?

**Comment by rjrudin** [comment] 2017-11-28 18:34
Which version of ml-gradle are you on? 2.9.0 - https://github.com/marklogic-community/ml-gradle/releases/tag/2.9.0 - includes support for figuring out the order in which to deploy roles. That also includes support for roles that refer to themselves.

**Comment by arulsiva21** [comment] 2017-11-29 12:43
I'm having this issue on below version while deploying role using mlDeployRoles 

------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Windows 10 10.0 amd64

**Comment by rjrudin** [comment] 2017-11-29 12:56
That's the Gradle version, not ml-gradle. The version of ml-gradle you're using is in your build.gradle file - what version is that?

**Comment by rjrudin** [comment] 2017-11-29 12:57
Also, assuming you're on 2.9.0 or greater, are you able to share the set of roles that you're deploying? I'd like to see those so that I can reproduce the problem.

**Comment by arulsiva21** [comment] 2017-11-29 12:58
Here you go...
plugins { 
  id "com.marklogic.ml-gradle" version "3.1.0"
}

**Comment by rjrudin** [comment] 2017-12-03 14:30
Thanks @arulsiva21 - I reproduced the problem. The code in ml-app-deployer will sort the role files based on their dependencies on other roles, but it's not taking into account permissions.

I'm about to release 3.2.0, I'll add a fix in there which was suggested to me before - the roles will be deployed twice; the first time, without any permissions or role dependencies (so that every role can be created), and the second time, with the permissions and role dependencies added back.

**Comment by arulsiva21** [comment] 2017-12-03 16:26
OK. Thanks!

**Comment by rjrudin** [comment] 2017-12-03 17:52
This is being fixed in 3.2.0 via https://github.com/marklogic-community/ml-app-deployer/issues/215

**Closed by rjrudin** 2017-12-03 17:52 UTC

**Comment by rjrudin** [comment] 2017-12-03 18:11
@arulsiva21 I recommend also removing all of the ML roles from your ml-config/security/roles directory. The export tool exports them because your application roles depend on them, but the export tool doesn't know the difference between ML roles and custom roles. It's best not to have ML roles checked into version control, as they can change between ML versions.

**Comment by arulsiva21** [comment] 2017-12-04 15:10
ok... i've same problem on deploying databases using mlDeployDatabases.
I see databases also expects the same ordering. For eg: when trigger db points to an another databases which is not created at that time throws error saying database not found.

**Comment by rjrudin** [comment] 2017-12-05 12:43
Ah - ml-gradle doesn't yet support either trying to determine the order of databases or doing what it now does for roles - creating them without references to triggers/schemas/security databases, and then without. 

For now, the way to solve this is by naming the filenames so they reflect the order they should be deployed in - e.g. 1-content-database.json, 2-triggers-database-.json, etc.

**Comment by arulsiva21** [comment] 2017-12-05 12:45
Yes.. We resolved it by renaming. Thanks for your clarification!
