### ISSUE TITLE
mlUndeployTasks doesn't undeploy scheduled tasks with ml-gradle 3.10.0 version

### ISSUE THREAD

**Issue by mukeshpuram** [marklogic-community/ml-gradle#427] opened 2019-02-03 22:29 UTC
Observed the mlUndeployTasks not working from ml-gradle 3.10.0 version. Could not able to Undeploy Tasks where as mldeleteAllTasks working fine. everything looks good for the same with ml-gradle 3.9.0 version.

**Comment by rjrudin** [comment] 2019-02-04 13:46
Can you share 2 or more of the tasks you're deploying? 

Also, try using curl to make the same DELETE calls that ml-gradle is, which you can see by running "gradle -i mlUndeployTasks".

**Comment by mukeshpuram** [comment] 2019-02-04 17:34
Please find the 2 tasks details as below
Objective : task-path will be same and only task-database, task-modules and task-user differs

JSON : Task1
DATABASE : project-content
MODULES_DATABASE : project-modules
NAME : project

{
  "task-enabled":true,
  "task-path":"/ext/schedules/scheduled-task.xqy",
  "task-root":"/",
  "task-type":"minutely",
  "task-period":1,
  "task-database":"%%DATABASE%%",
  "task-modules":"%%MODULES_DATABASE%%",
  "task-user":"%%NAME%%-creator",
  "task-priority":"normal"
}

JSON - Task2
DATABASE : app-content
MODULES_DATABASE : app-modules
NAME : app

{
  "task-enabled":true,
  "task-path":"/ext/schedules/scheduled-task.xqy",
  "task-root":"/",
  "task-type":"minutely",
  "task-period":1,
  "task-database":"%%DATABASE%%",
  "task-modules":"%%MODULES_DATABASE%%",
  "task-user":"%%NAME%%-creator",
  "task-priority":"normal"
}

**Note** : I tried mlDeployTasks with single scheduled task and I can able to deploy the task but when tried mlUndeployTasks for the same task , it does not Undeploy the task. The mlUndeployTasks does not work whether it is a single task or multiple tasks.

Observation with ml-gradle 3.9.0 and 3.10.0 
     _gradle -i mlUndeployTasks_
In ml-gradle 3.10.0 , the task not Sending DELETE request while running mlUndeployTasks where as I can see below in 3.9.0 version

Sending XML GET request as user 'deployUser' to path: /manage/v2/tasks?group-id=Default
Deleting task at path /manage/v2/tasks/13518725656074084261?group-id=Default
Sending  DELETE request as user 'deployUser' to path: /manage/v2/tasks/13518725656074084261?group-id=Default

**Comment by rjrudin** [comment] 2019-02-08 19:00
I tried this out locally, but I couldn't reproduce the bug. My initial thought was you had the same task-database for both scheduled tasks, which would lead to only one scheduled task being deployed. But that's not the case, each scheduled task has a different task-database, which means they both get deployed. 

My hunch is that your ML user that is deleting the tasks - deployUser - does not have the "security" role, and the ML Manage API may be preventing the delete from occurring. I did deploy and undeploy as the "admin" user, and I didn't run into any issues.

Here's the logging I got:

Undoing command [com.marklogic.appdeployer.command.tasks.DeployScheduledTasksCommand] with sort order [1000]
Processing files in directory: /Users/rrudin/dev/workspace/ml-gradle/examples/427-project/src/main/ml-config/tasks
Processing file: /Users/rrudin/dev/workspace/ml-gradle/examples/427-project/src/main/ml-config/tasks/task1.json
Sending XML GET request as user 'admin' to path: /manage/v2/tasks?group-id=Default
Checking for existence of resource: 16449516109762432823
Sending XML GET request as user 'admin' to path: /manage/v2/tasks?group-id=Default
Sending XML GET request as user 'admin' to path: /manage/v2/tasks?group-id=Default
Deleting task at path /manage/v2/tasks/16449516109762432823?group-id=Default
Sending  DELETE request as user 'admin' to path: /manage/v2/tasks/16449516109762432823?group-id=Default
Deleted task at path /manage/v2/tasks/16449516109762432823?group-id=Default
Processing file: /Users/rrudin/dev/workspace/ml-gradle/examples/427-project/src/main/ml-config/tasks/task2.json
Sending XML GET request as user 'admin' to path: /manage/v2/tasks?group-id=Default
Checking for existence of resource: 778330226768424218
Sending XML GET request as user 'admin' to path: /manage/v2/tasks?group-id=Default
Sending XML GET request as user 'admin' to path: /manage/v2/tasks?group-id=Default
Deleting task at path /manage/v2/tasks/778330226768424218?group-id=Default
Sending  DELETE request as user 'admin' to path: /manage/v2/tasks/778330226768424218?group-id=Default
Deleted task at path /manage/v2/tasks/778330226768424218?group-id=Default
Finished undoing command [com.marklogic.appdeployer.command.tasks.DeployScheduledTasksCommand]

**Comment by rjrudin** [comment] 2019-02-16 23:39
Closing this, please reopen if it's still a problem and you're sure that the user doing the deployment has the "security" role.

**Closed by rjrudin** 2019-02-16 23:39 UTC
