### ISSUE TITLE
Task mlExportResources doesn't export cpf-config

### ISSUE THREAD

**Issue by uouake** [marklogic-community/ml-gradle#552] opened 2020-05-13 18:43 UTC
Hi, i'm trying to migrate an existing Roxy project to ml-gradle and i found problem with task mlExportResources.

Let say my application name is **IBO** and version app is : 
```
marklogic-version = 8.0-5
roxy-version = 1.7.2
ml-gradle-version = 3.17.0
```

Content of file `build.gradle` is : 
```
plugins {
    id "net.saliman.properties" version "1.4.6"
    id "com.marklogic.ml-gradle" version "3.17.0"
}
```

Content of file `gradle-dev.properties` is : 
```
mlAppName=ibo
mlRestPort=8020
mlPassword=admin
mlUsername=admin
mlHost=localhost
mlTriggersDatabaseName=ibo-triggers
mlModulesDatabaseName=ibo-modules
```

Content of properties file `mig_roxy_gradle.properties` for export resource task is : 
```
cpfConfigs=RM Domain
databases=ibo-content,ibo-modules,ibo-triggers
domains=RM Domain
pipelines=RM Pipeline
roles=ibo-role
servers=ibo,ibo-xcc
triggers=ibo-triggers
users=ibo-user
```

When i run `gradle mlExportResources -PpropertiesFile=/roxy/deploy/mig_roxy_gradle.properties -PenvironmentName=dev -i`, i have : 

```
> Configure project :
Evaluating root project 'ml-gradle' using build file '/ml-gradle-test/build.gradle'.
PropertiesPlugin:apply Loaded 61 properties from /ml-gradle-test/gradle.properties
PropertiesPlugin:apply Loaded 6 properties from /ml-gradle-test/gradle-dev.properties
PropertiesPlugin:apply Loaded 0 properties from environment variables
PropertiesPlugin:apply Loaded 0 properties from system properties
PropertiesPlugin:apply Loaded 2 properties from the command line

Initializing ml-gradle
Admin interface host: 172.19.31.22
Admin interface username: admin
App name: intellibo
App host: localhost
Not creating REST server if no REST config file is found
App REST port: 8020
App REST authentication: digest
REST admin username: admin
App Services username: admin
Triggers database name: intellibo-int-triggers
Content forests per host: 1
Content database name: ${app-name}-content
Modules database name: ${app-name}-modules
Group name: Default
Manage host: localhost
Manage username: admin
Manage user with security role: admin
Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: admin, security username: admin]
Finished initializing ml-gradle

All projects evaluated.
Selected primary task 'mlExportResources' from project :
Tasks to be executed: [task ':mlExportResources']
:mlExportResources (Thread[Execution worker for ':',5,main]) started.

> Task :mlExportResources
Caching disabled for task ':mlExportResources' because:
  Build cache is disabled
Task ':mlExportResources' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Exporting resources to: /ml-gradle-test/src/main/ml-config
Will export servers and tasks in group: Default
Sending JSON GET request as user 'admin' to path: /manage/v2/databases/null/cpf-configs/RM Domain/properties
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"404", "status":"Not Found", "messageCode":"XDMP-NOSUCHDB", "message":"XDMP-NOSUCHDB: xdmp:database(\"null\") -- No such database null"}}

> Task :mlExportResources FAILED
:mlExportResources (Thread[Execution worker for ':',5,main]) completed. Took 3.11 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlExportResources'.
> 404 Not Found

```

Export resources work for databases and forests. Its not working for cpf-configs and domains, i have `null` for databases when `Sending JSON GET request as user 'admin' to path: /manage/v2/databases/**null**/cpf-configs/RM Domain/properties`. However, i mention in `gradle-dev.properties` the value of trigger database.

Could someone please help me with this ?

**Comment by rjrudin** [comment] 2020-05-13 18:49
This looks like a regression from the removal of "mlTriggersDatabaseName". 

Try adding this as a workaround:

```
ext {
  mlAppConfig.triggersDatabaseName = "ibo-triggers"
}

**Comment by uouake** [comment] 2020-05-13 19:32
I try it, same error.

**Comment by rjrudin** [comment] 2020-05-14 02:40
I took a quick look at this and got the same error with the cpf-example project. I tried what I think is the exact same approach just using the ml-app-deployer library, and it worked fine. Not sure what the issue is in ml-gradle yet, will check it out again tomorrow.

**Comment by rjrudin** [comment] 2020-05-14 02:49
Argh - I see the issue now; the triggers database is assigned to the Exporter after the resources are selected. 

This is a trivial fix; would you prefer a 3.17.1 release, or would you be able to upgrade to the 4.0 baseline and use a 4.0.x release?

**Comment by uouake** [comment] 2020-05-14 06:39
Oh good, i prefer to use a 3.17.1. At the moment, it’s not possible for me to upgrade to the 4.0 baseline.

**Closed** 2020-05-14 14:16 UTC

**Comment by rjrudin** [comment] 2020-05-14 14:19
Here's the 3.17.1 release - https://github.com/marklogic-community/ml-gradle/releases/tag/3.17.1
