### ISSUE TITLE
TDE deployment issues

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/ml-gradle#601] opened 2021-08-06 07:26 UTC
Hi,

I have now a second client which have TDE deployment issues.  This happens if you have on you local disk more than 1 TDE with the same schema/view and also on the server, and you make changes in the TDE local. The TDE machinery does not look to the whole picture. So you have 2 TDE local with MySchema/MyView with MyColumn "not nullable"  and on the server those 2 are "nullable", then deploying fails, because the first TDE is evaluated against the already deployed second TDE which is conflicting. However the end-state is non conflicting, because I am also going to update the second TDE. 

My previous ticket for another client ( https://github.com/marklogic-community/ml-gradle/issues/532 ) and related one ( https://github.com/marklogic-community/ml-gradle/issues/459 ) are focussed on (or framed in terms of solution to) turning off pre validation. 

However this is not going to help, because this is a server limitation. I have discussed this with Yash and Fayez, and it seems undoable for 10.0-8 to support "TDE batch insert". 

A work around would be to implement this in gradle using the following algorithm. This only need to be done if there are local more than 1 TDE with the same schema/view which has also remote more than 1 TDE. 

I think the right algorithm is:

```
 uniqueSchemaViewLocal = DISTINCT(local disk TDE schema/view)
 for each uniqueSchemaViewLocal in uniqueSchemaViewsLocal
   if (count(local disk TDE with schema/view) > 1 and count(server side TDE with schema/view) > 1 then
     disable (tde:enable=false) all server TDE with this schema/view only the ones which I plan to deploy
 .. regular deployment procedure..
```

**Comment by josvanroosmalen** [comment] 2021-08-06 07:30
There might be some **risks** involved in this workaround -> if we disable the serverside TDE which we plan to deploy, and then the deploys fails (permission errors/network/connectivity errors), then the customer is stuck with reindexing activity (to disable it), disabled views.

**Comment by josvanroosmalen** [comment] 2021-08-06 07:35
Internal tracking: https://bugtrack.marklogic.com/54902

**Comment by rjrudin** [comment] 2021-08-06 13:29
This seems like an unusual scenario, and due to the root cause being a server issue, I am going to close this as I do not see ml-gradle getting into the business here of complex, potentially risky workarounds for server issues. 

I would consider a PR though, as that would give me a better chance to understand and assess the risks. Most of the work I believe would happen in ml-javaclient-util - DefaultSchemasLoader and TdeDocumentFileProcessor.

**Closed by rjrudin** 2021-08-06 13:29 UTC
