### ISSUE TITLE
mlAddHost into non-default group issue tracking restart

### ISSUE THREAD

**Issue by hgarrow** [marklogic-community/ml-gradle#332] opened 2018-03-27 17:33 UTC
Hi -

I am adding hosts to a non-Default group using ml-gradle and it appears to be working, but I get 30 instances of 404 monitoring the restart of the group. It appears to be watching for a restart of Default instead of my non-Default group.

My command:
gradle -PenvironmentName=newProd -Phost='mlhostg4.mydomain.com' -PhostGroup='mygroup04' mlAddHost

The Error I see: 
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"404", "status":"Not Found", "messageCode":"", "message":"URI /admin/v1/timestamp does not exist."}}
Reached limit of 30, and MarkLogic has not restarted yet; check MarkLogic status

**Comment by rjrudin** [comment] 2018-03-28 01:56
Can you this with "-i" so we can see after which call to ML ml-gradle starts waiting for a restart? Also, does group "mygroup04" have an Admin server instance within it?

**Comment by hgarrow** [comment] 2018-03-28 13:58
Yes, each group has an Admin server instance. I removed the host and re-added it with the -i flag, but I am not seeing any extra information.

Output attached.

**Comment by rjrudin** [comment] 2018-03-30 00:36
How many hosts do you have in your cluster when you add a new one? I'll try to reproduce this locally. 

Which version of ML are you on too?

**Comment by hgarrow** [comment] 2018-03-30 12:13
This cluster I am building up has 61 total hosts in it, however, this happens even at two hosts.

Current MarkLogic version is 8.0-8

**Comment by rjrudin** [comment] 2018-04-10 18:05
Are you able to test this on 9.0-4, or do you have to stick with 8.x?

**Comment by hgarrow** [comment] 2018-04-10 18:07
We are sticking with 8.x for now.

**Comment by rjrudin** [comment] 2018-04-10 18:15
I just got the same error with a cluster that's on 8.0-7.1 - trying 9.x next.

**Comment by rjrudin** [comment] 2018-04-10 18:45
I mis-spoke - the problem isn't the missing Manage server (that's a separate issue), it's that the rewriter on the newly added Admin server is incorrect.

If you set the rewriter on the Admin server in your group to "rewriter.xqy", then you shouldn't see this problem. 

I believe this is fixed in ML 9.0-4, not sure which version of ML 9 it was fixed in though.

**Closed** 2018-04-10 18:53 UTC
Labels: MarkLogic bug
