### ISSUE TITLE
mlImportWorkspaces throws error for MarkLogic 9.

### ISSUE THREAD

**Issue by grechaw** [marklogic-community/ml-gradle#187] opened 2017-04-04 19:23 UTC
Not surprising, since it relies on a non-public API.

Here's what happens when I try to run it:

```
ovider.entity.MimeMultipartProvider is not found. The component is ignored.
Releasing connection
:mlImportWorkspaces FAILED
:mlImportWorkspaces (Thread[Daemon worker Thread 4,5,main]) completed. Took 1.769 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlImportWorkspaces'.
> Local message: failed to apply resource at eval: Internal Server Error. Server Message: XDMP-UNDFU
N: (err:XPST0017) Undefined function qconsole-model:default-content-source()

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.


BUILD FAILED
```

I found that a workaround is to hack the qconsole-model function (not the right fix) by adding this function:

```
 declare function qconsole-model:default-content-source(
 ) as xs:unsignedLong
 {
     qconsole-model:default-database()
 };
```

By deduction I posit that ml-gradle (or app deployer) need only to replace the call to `default-content-source` with `default-database` and it will work again.

**Comment by rjrudin** [comment] 2018-02-17 16:33
Duplicate of https://github.com/marklogic-community/ml-javaclient-util/issues/92

**Closed by rjrudin** 2018-02-17 16:33 UTC
Labels: bug
