### ISSUE TITLE
corb2-project fails when running gradle task corbDeployed

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/ml-gradle#373] opened 2018-08-29 07:54 UTC
I just tested the corb2-project and I ran into the following issue:
Just did plain old gradle mlDeploy and then gradle corbDeployed -i
I have one single document in the database so I would expect the corbtask to output a singel line in the logfile. Find below my error message.

```
gradle corbDeployed -i
Initialized native services in: /Users/pkester/.gradle/native
Using 8 worker leases.
Starting Build
Settings evaluated using settings file '/Users/pkester/Documents/GitHub/ml-gradle/examples/corb2-project/settings.gradle'.
Projects loaded. Root project using build file '/Users/pkester/Documents/GitHub/ml-gradle/examples/corb2-project/build.gradle'.
Included projects: [root project 'corb2-project']

> Configure project :
Evaluating root project 'corb2-project' using build file '/Users/pkester/Documents/GitHub/ml-gradle/examples/corb2-project/build.gradle'.

Initializing ml-gradle
Admin interface host: localhost
Admin interface username: admin
App name: corb2-project
App host: localhost
App REST port: 8140
REST admin username: admin
App Services username: admin
Manage host: localhost
Manage username: admin
Manage user with security role: admin
Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: admin, security username: admin]
Finished initializing ml-gradle

All projects evaluated.
Selected primary task 'corbDeployed' from project :
Tasks to be executed: [task ':mlPrepareRestApiDependencies', task ':mlLoadModules', task ':corbDeployed']
:mlPrepareRestApiDependencies (Thread[Task worker for ':' Thread 6,5,main]) started.

> Task :mlPrepareRestApiDependencies
Task ':mlPrepareRestApiDependencies' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:mlPrepareRestApiDependencies (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 0.079 secs.
:mlLoadModules (Thread[Task worker for ':' Thread 6,5,main]) started.

> Task :mlLoadModules
Task ':mlLoadModules' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Initializing new instance of ModulesLoader
Loading asset modules from dir: src/main/ml-modules
Initializing ExecutorService 
Initializing ExecutorService 
Shutting down ExecutorService
Loading all non-asset modules from dir: src/main/ml-modules
Initializing ExecutorService 
Shutting down ExecutorService
Releasing connection
:mlLoadModules (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 0.166 secs.
:corbDeployed (Thread[Task worker for ':' Thread 6,5,main]) started.

> Task :corbDeployed FAILED
Task ':corbDeployed' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:corbDeployed (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 0.169 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':corbDeployed'.
> Cannot get the value of write-only property 'argsString' for task ':corbDeployed' of type com.marklogic.gradle.task.CorbTask.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
3 actionable tasks: 3 executed

```

Is this a version issue?
I'm running on ML 9.0-4 on mac with gradle 4.9, ml-gradle 3.6.0 and corb 2.3.2 as specified in the build.gradle file from the examples project.

Which specific version of gradle and ml-gradle do I need to get this to work?
If I up the ml-gradle version to 3.8.1 and corb to 2.4.0 I get the follwoing error:
```
gradle corbDeployed -i
Initialized native services in: /Users/pkester/.gradle/native
Using 8 worker leases.
Starting Build
Settings evaluated using settings file '/Users/pkester/Documents/GitHub/ml-gradle/examples/corb2-project/settings.gradle'.
Projects loaded. Root project using build file '/Users/pkester/Documents/GitHub/ml-gradle/examples/corb2-project/build.gradle'.
Included projects: [root project 'corb2-project']

> Configure project :
Evaluating root project 'corb2-project' using build file '/Users/pkester/Documents/GitHub/ml-gradle/examples/corb2-project/build.gradle'.

Initializing ml-gradle
Admin interface host: localhost
Admin interface username: admin
App name: corb2-project
App host: localhost
App REST port: 8009
REST admin username: admin
App Services username: admin
Manage host: localhost
Manage username: admin
Manage user with security role: admin
Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: admin, security username: admin]
Finished initializing ml-gradle

All projects evaluated.
Selected primary task 'corbDeployed' from project :
Tasks to be executed: [task ':mlPrepareRestApiDependencies', task ':mlLoadModules', task ':corbDeployed']
:mlPrepareRestApiDependencies (Thread[Task worker for ':' Thread 7,5,main]) started.

> Task :mlPrepareRestApiDependencies
Task ':mlPrepareRestApiDependencies' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:mlPrepareRestApiDependencies (Thread[Task worker for ':' Thread 7,5,main]) completed. Took 0.081 secs.
:mlLoadModules (Thread[Task worker for ':' Thread 7,5,main]) started.

> Task :mlLoadModules
Task ':mlLoadModules' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Initializing new instance of ModulesLoader
Loading asset modules from dir: src/main/ml-modules
Initializing ExecutorService 
Initializing ExecutorService 
Shutting down ExecutorService
Loading all non-asset modules from dir: src/main/ml-modules
Initializing ExecutorService 
Shutting down ExecutorService
Releasing connection
:mlLoadModules (Thread[Task worker for ':' Thread 7,5,main]) completed. Took 0.13 secs.
:corbDeployed (Thread[Task worker for ':' Thread 7,5,main]) started.

> Task :corbDeployed FAILED
Task ':corbDeployed' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:corbDeployed (Thread[Task worker for ':' Thread 7,5,main]) completed. Took 0.041 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':corbDeployed'.
> java.lang.UnsupportedOperationException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
3 actionable tasks: 3 executed
```

**Comment by peetkes** [comment] 2018-08-29 08:35
If I resort to use the gradle wrapper (which uses gradle 3.3) it works as expected.
Even if I up ml-gradle to 3.8.1 and corb to 2.4.0

**Comment by peetkes** [comment] 2018-08-29 08:44
It works with gradle 4.2 and lower. gradle 4.3 and higher fail with that unsupportedOperationExecption

**Comment by hansenmc** [comment] 2018-09-01 22:04
Running with `--stacktrace` reveals that the call to `org.gradle.api.internal.AbstractTask.getValidators(AbstractTask.java:684)` threw an `UnsupportedOperationException`

> 17:15:08.093 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: **java.lang.UnsupportedOperationException**
> 17:15:08.093 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at **org.gradle.api.internal.AbstractTask.getValidators(AbstractTask.java:684)**
> 17:15:08.093 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
> 17:15:08.093 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
> 17:15:08.093 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
> 17:15:08.093 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
> 17:15:08.093 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.marklogic.gradle.task.CorbTask_Decorated.getProperty(Unknown Source)
> 17:15:08.093 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at **com.marklogic.gradle.task.CorbTask$_collectMemberVariables_closure4.doCall(CorbTask.groovy:156)**
 
The CorbTask was attempting to [collect the member variables](https://github.com/marklogic-community/ml-gradle/blob/master/src/main/groovy/com/marklogic/gradle/task/CorbTask.groovy#L156) in a closure that accesses Task properties.

It appears that the method `getValidators()` was recently removed from the Gradle AbstractTask class, but something is still expecting to invoke that method:
https://github.com/gradle/gradle/commit/30c7dcbd1363d830392c6a8a11be58becf0d0bed#diff-5a073fcafa933576d519372602f7d109 

So, something seems to have been relying on what was deprecated, and now removed, methods. Need to dig in and see where/why it was trying to invoke the `getValidators()`, or to wrap with a try/catch to handle the issue.

**Comment by hansenmc** [comment] 2018-09-02 20:50
Okay, I think I see where this is happening. When iterating through the metaClass properties to see if their values should be collected and set in the `corbOptions`, some of the properties, such as `argsString` and `validators`, cause these exceptions to be thrown.

It looks like we can avoid the issues by reordering the conditions in the if statement. If the property name isn't one of the corbOptions keys, then no need to access it and test if it exists.

    if (corbOptions[corbOptionKey] && this[it.name]) {
        [(corbOptions[corbOptionKey]): this[it.name] ]
    } else {
        [:]
instead of:

    if (this[it.name] && corbOptions[corbOptionKey]) {
        [(corbOptions[corbOptionKey]): this[it.name] ]
    } else {
        [:]

I'll do some more testing and try to get a PR submitted.

**Comment by rjrudin** [comment] 2018-09-07 11:48
@hansenmc I believe this is fixed now via your PR?

**Comment by hansenmc** [comment] 2018-09-07 11:56
Yes, I was able to reproduce and the change in the PR resolved it.

**Comment by rjrudin** [comment] 2019-08-23 17:59
@hansenmc I verified that this error doesn't happen with Gradle 3.5, but it fails on 4.10.2 with an UnsupportedOperationException, and on 5.4.1, it gets the "argsString" error mentioned in this ticket. 

So I'll leave this open, but I'm wondering if the solution is to just declare properties for each Corb input.

**Comment by hansenmc** [comment] 2019-08-23 18:10
Yeah, the meta-programming fanciness may not be worth it. CoRB options don't change that much. I'll submit a PR with them hard-coded (and bump to the latest version of CoRB 2.4.5)

**Comment by hansenmc** [comment] 2019-09-02 21:35
The "argsString" error should have been resolved by changes discussed earlier in this issue to adjust the order of operation when testing existence of corbOptions. 

However, the `examples/corb2-project` has not been updated to use a recent version of ml-gradle. 

I tried:
```
cd examples/corb2-project
./gradlew wrapper --gradle-version 5.4.1
./gradlew corbDeployed -i
```
and was able to observe the "argString" error.

After updating the ml-gradle dependency to `3.16.0` and re-running, it works fine.

I also setup a corb task in the local-testing-project and ran with Gradle 5.4.1 as well and was able to generate an error when running with `--no-daemon` that seems to appear occasionally for some people:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':corbDeployed'.
> > Could not get unknown property 'corbOptions' for task ':corbDeployed' of type com.marklogic.gradle.task.CorbTask.

If I make the `corbOptions` a class variable, instead of a metaClass variable, I am not able to reproduce the issue.

    class CorbTask extends JavaExec {

        def corbOptions = [:]

I'll put together a pull request to update the ml-gradle version in the `examples/corb2-project/build.gradle` and to make the other adjustment to the CorbTask. These changes should make the task more reliable and avoid the other spurious errors that users have been seeing.

In order to help avoid similar issues in the future, it might be a good idea to update the dependencies for the example projects as part of the release process, or at least occasionally perform a review and mass update, such as annually when copyright year is updated in disclaimer headers.

**Comment by hansenmc** [comment] 2019-09-03 04:04
Regarding the issue of keeping dependencies up to date, using something like https://dependabot.com/ is helpful. It can be configured to watch the main gradle build, as well as the gradle projects in the examples directories, and it will auto-submit pull requests to bump dependencies

**Closed** 2019-11-13 16:14 UTC
