### ISSUE TITLE
CorbTask not working with Corb 2.5.1 or 2.5.2

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-gradle#597] opened 2021-07-21 13:27 UTC
Can reproduce this in the Corb example project with the following config:

- ml-gradle 4.2.0 or 4.2.1 (4.1.x doesn't work with Corb 2.5.x, and that issue was fixed in 4.2)
- Corb 2.5.1
- Gradle 6.4 to 6.9 (can't use 6.3 because of a breaking change in between Gradle 6.3 and 6.4)

Running "./gradlew corbDeployed" produces an odd error of:

```
Error: Could not find or load main class com.marklogic.developer.corb.Manager
:corbDeployed (Thread[Execution worker for ':',5,main]) completed. Took 0.113 secs.
```

Corb 2.5.0 runs fine.

**Comment by rjrudin** [comment] 2021-07-21 13:28
@hansenmc No rush on solving this, as Corb 2.5.0 is running fine.

**Comment by hansenmc** [comment] 2021-07-21 14:26
Interesting, I can reproduce the issue.

I see a difference in the classpath (it's missing the CoRB jar), which explains why it complains that the Manager class is not found.

Looking at the local cache directories, I see that 2.5.1 and 2.5.2 only have the pom.xml, but 2.5.0 has the pom.xml and the jar. Seems something is going wrong resolving and downloading the jar file.

Looking at Maven Central, it seems that the corb jar was published differently, and has "-all" appended to the name:
- marklogic-corb-2.5.2-all.jar  
- marklogic-corb-2.5.1-all.jar   
- marklogic-corb-2.5.0.jar   

https://repo1.maven.org/maven2/com/marklogic/marklogic-corb/2.5.2/
https://repo1.maven.org/maven2/com/marklogic/marklogic-corb/2.5.1/
https://repo1.maven.org/maven2/com/marklogic/marklogic-corb/2.5.0/

I had been publishing to MavenCentral using Bintray sync, so maybe there was a recent change/issue with that. I'll have to see how to get the jar renamed or uploaded with the correct naming convention.

**Comment by hansenmc** [comment] 2021-12-23 16:07
I found that the issue was due to shadowjar and classifier. 
https://github.com/johnrengelman/shadow/issues/378#issuecomment-389594943

Setting `classifier = null` ensures that the jar filename doesn't have "-all" appended. CoRB 2.5.3 was just published and has the expected jar filename. So, it should play nicer with ml-gradle for the corb task.

**Comment by hansenmc** [comment] 2021-12-24 20:56
With CoRB 2.5.3 I am able to get things working by applying the following:

```
configurations {
    // This configuration captures the dependencies for running CoRB (Content Reprocessing in Bulk).
    // This is only needed if you want to run corb via Gradle tasks.
    // If you do, using com.marklogic.gradle.task.CorbTask is a useful starting point, as shown below.
    corb {
      attributes {
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
      }
  }
}

dependencies {
    // required to run CoRB2
    corb "com.marklogic:marklogic-corb:${corbVersion}"
    corb 'com.marklogic:marklogic-xcc:10.0.8'
    // optional
    //corb 'org.jasypt:jasypt:1.9.2' // would be necessary to leverage JasyptDecrypter
}
```

Without applying the attributes to the `corb` configuration, there is a message about multiple variants:

> Could not resolve all files for configuration ':corb'.
   > Could not resolve com.marklogic:marklogic-corb:2.5.3.
     Required by:
         project :
      > Cannot choose between the following variants of com.marklogic:marklogic-corb:2.5.3:
          - runtimeElements
          - shadowRuntimeElements
        All of them match the consumer attributes:
          - Variant 'runtimeElements' capability com.marklogic:marklogic-corb:2.5.3:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.jvm.version '8' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
          - Variant 'shadowRuntimeElements' capability com.marklogic:marklogic-corb:2.5.3:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'shadowed' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it

And then after applying the attributes, it seems that it isn't resolving the XCC transitive dependency, so I need to add an explicit dependency.

I'll look and see if there are additional adjustments that I need to make to the shadow plugin config that is generating the CoRB fat jar that can make this easier and more simple, but for now the workaround above will work with 2.5.3. I'll submit a PR with these changes (as well as removing `jcenter()` and replacing with `mavenCentral()` in the CoRB example project.

**Closed** 2022-08-08 16:13 UTC

**Comment by grtjn** [comment] 2022-10-05 16:05
Wanted to report that I am still seeing issues with 2.5.3 and 2.5.4. Gradle is showing this line in the console, note the .module extension, rather than .jar:

    Downloading https://repo.maven.apache.org/maven2/com/marklogic/marklogic-corb/2.5.4/marklogic-corb-2.5.4.module to C:\Users\josten\AppData\Local\Temp\gradle_download7794637644240380108bin

And then it invokes corb as usual, but the classpath seems to be missing the corb jar:

```
... -cp C:\Users\josten\.gradle\caches\modules-2\files-2.1\org.webjars\angularjs\1.8.2\7a971be489a3f321b2db104e2a45afaa633e040d\angularjs-1.8.2.jar;C:\Users\josten\.gradle\caches\modules-2\files-2.1\org.webjars\bootstrap\3.4.1\2c6a8508a4f1484abcaf334cf2fe3df97cf93eac\bootstrap-3.4.1.jar;C:\Users\josten\.gradle\caches\modules-2\files-2.1\org.webjars\jquery\3.6.0\633447ad320c04c69fb621d08ba2268f50822eee\jquery-3.6.0.jar;C:\Users\josten\.gradle\caches\modules-2\files-2.1\com.google.code.externalsortinginjava\externalsortinginjava\0.6.0\cf55d839cef1c5148b337e4d5d8d6f75204a4f72\externalsortinginjava-0.6.0.jar;C:\Users\josten\.gradle\caches\modules-2\files-2.1\com.marklogic\marklogic-xcc\10.0.9\ccdfd874cab1081685aabf92e59e624b41ef81da\marklogic-xcc-10.0.9.jar;C:\Users\josten\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-csv\1.4\fc2512d2109144df353501266ac4bbe179058afd\commons-csv-1.4.jar com.marklogic.developer.corb.Manager
Successfully started process 'command 'C:\Program Files\Java\jdk-11.0.11\bin\java.exe''
Error: Could not find or load main class com.marklogic.developer.corb.Manager
```
